# Project information
site_name: Flet Material Library
site_author: S. Ahmad P. Hakimi
site_description: >-
  UI component library built with Flet.

# Repository
repo_name: material_design_flet
repo_url: https://github.com/LineIndent/material_design_flet

# copyright
copyright: Copyright &copy; 2023 S. Ahmad P. Hakimi

# page tree
nav:
  - Home: index.md
  - Controls:
      - controls/index.md
      - Annotations: controls/annotations.md
      - Alerts: controls/alerts.md
      - Badges: controls/badges.md
      - Buttons: controls/buttons.md
      - Checkboxes: controls/checkboxes.md
      - Chips: controls/chips.md
      - Dropdowns: controls/dropdowns.md
      - Switches: controls/switches.md
  - Contribute: contribute.md

theme:
  name: material
  # favicon: images/favicon.png
  # logo:
  palette:
    scheme: slate
    primary: cyan
    accent: cyan
  font:
    text: Roboto

  extra_css:
    - https://use.fontawesome.com/releases/v5.15.3/css/all.css
    - stylesheets/extra.css

  icon:
    repo: fontawesome/brands/git-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      line_spans: __span
      anchor_linenums: true
      pygments_lang_class: true
      linenums_style: pymdownx-inline
      use_pygments: true
  - toc:
      permalink: false
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - abbr
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  generator: false
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@lineindent

    - icon: fontawesome/brands/github
      link: https://github.com/LineIndent

    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/user?u=87176956
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

docs_dir: docs
